apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"run":"busybox"},"name":"busybox","namespace":"default"},"spec":{"containers":[{"image":"gitea.bongeunsa.net:3000/devops_prod/busybox:1.32","name":"busybox","resources":{}}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"regcred"}],"restartPolicy":"Always"},"status":{}}
  creationTimestamp: "2023-06-26T04:21:26Z"
  labels:
    run: busybox
  name: busybox
  namespace: default
  resourceVersion: "1441613"
  uid: c12a814f-05fb-4451-9f0b-3f6b39cde442
spec:
  containers:
  - image: gitea.bongeunsa.net:3000/devops_prod/busybox:1.32
    imagePullPolicy: IfNotPresent
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9b7bn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: regcred
  nodeName: ip-10-0-0-30.ap-northeast-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-9b7bn
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-06-26T04:21:26Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-06-26T04:21:26Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-06-26T04:21:26Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-06-26T04:21:26Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: gitea.bongeunsa.net:3000/devops_prod/busybox:1.32
    imageID: ""
    lastState: {}
    name: busybox
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "gitea.bongeunsa.net:3000/devops_prod/busybox:1.32"
        reason: ImagePullBackOff
  hostIP: 10.0.0.30
  phase: Pending
  podIP: 10.0.0.137
  podIPs:
  - ip: 10.0.0.137
  qosClass: BestEffort
  startTime: "2023-06-26T04:21:26Z"
