apiVersion: v1
kind: Pod
metadata:
  name: pod-liveness
  labels:
    app: liveness
spec:
  containers:
  - name: pod-liveness
    image: kubetm/app
    ports:
    - containerPort: 8080
  terminationGracePeriodSeconds: 0
